str="wELcome To python"
print(str.capitalize())
print(str.upper())
print(str.lower())
print(str.swapcase())
print(str.title())
print(str.split())
print(str.center(20,"$"))
print(str.count("o"))
print(str.replace("T","u"))
print(str.join("t "))
print(str.isupper())
print(str.islower())
print(str.isalpha())
print(str.isalnum())
print(str.isdigit())
print(str.isspace())
print(str.istitle())
print(str.startswith("d"))
print(str.endswith("m"))
print(str.find("e"))
print(len(str))
print(min(str))
print(max(str))
